### ISSUE TITLE
Mod version for 20.2 neoforge

### ISSUE THREAD

**Issue by kirderf1** [Commoble/infiniverse#1]
As a developer for [a mod that uses Infiniverse as a dependency](https://github.com/lunar-sway/minestuck), I am interested in seeing Infiniverse updated to minecraft 1.20.2 for neoforge.

If necessary or relevant, I am fine with helping out with the code update process.

What are the prospects for this?

**Comment by Commoble** [comment]
I'm waiting for 1.21 before I release the next update

**Comment by kirderf1** [comment]
Alright, and my interest or offer to help isn't enough to change that, I take it?

**Comment by Commoble** [comment]
It's not a matter of needing help, I've been preparing changes on the future branch and they seem to work; I just don't want to publish anything while neoforge is still in unstable beta.

https://github.com/Commoble/infiniverse/tree/future

The hacky registry hacks work even if multiple mods are doing it, so you're welcome to paste them into your own mod if you need them (e.g. mcjty's dimension mods do the same thing to get infinite dimensions working)
