### ISSUE TITLE
As of 1.0.0.5, the mod is required client-side when installed server-side

### ISSUE THREAD

**Issue by TheFlash787** [Commoble/infiniverse#4]
Was this intended?

![image](https://github.com/Commoble/infiniverse/assets/25883284/17707372-83ec-4058-a303-8c9ae745b488)

**Comment by Commoble** [comment]
Not intended, will attempt to fix it

**Comment by TheFlash787** [comment]
Hey, is it possible to backport this change into the 1.20.1 branch?
